# Adult Dataset

Link: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

In [27]:
import pandas as pd
from ucimlrepo import fetch_ucirepo
import numpy as np
import json
import os

pd.set_option('display.max_columns', None)

In [2]:
DATA_PATH = "../data/raw/adult"

In [44]:
train_df = pd.read_csv(f"{DATA_PATH}/adult.data", header = None, skipinitialspace=True)

In [45]:
train_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# missing values are represented as ?
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
dtype: int64

In [ ]:
df.iloc[:, 14].value_counts()

14
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [11]:
df.iloc[:, 14].value_counts(normalize=True)

14
<=50K    0.75919
>50K     0.24081
Name: proportion, dtype: float64

In [16]:
INFO_PATH = "../data/raw/adult"
name = "adult"

with open (f'{INFO_PATH}/{name}.json', 'r') as f:
    info = json.load(f)

In [17]:
info

{'name': 'adult',
 'task_type': 'binclass',
 'header': None,
 'column_names': ['age',
  'workclass',
  'fnlwgt',
  'education',
  'education.num',
  'marital.status',
  'occupation',
  'relationship',
  'race',
  'sex',
  'capital.gain',
  'capital.loss',
  'hours.per.week',
  'native.country',
  'income'],
 'num_col_idx': [0, 2, 4, 10, 11, 12],
 'cat_col_idx': [1, 3, 5, 6, 7, 8, 9, 13],
 'target_col_idx': [14],
 'file_type': 'csv',
 'data_path': 'data/raw/adult/adult.data',
 'test_path': 'data/raw/adult/adult.test',
 'column_info': {'age': 'float',
  'workclass': 'str',
  'fnlwgt': 'float',
  'education': 'str',
  'education.num': 'float',
  'marital.status': 'str',
  'occupation': 'str',
  'relationship': 'str',
  'race': 'str',
  'sex': 'str',
  'capital.gain': 'float',
  'capital.loss': 'float',
  'hours.per.week': 'float',
  'native.country': 'str',
  'income': 'str'},
 'train_num': 32561,
 'test_num': 16281}

In [21]:
num_col_idx = info['num_col_idx']
cat_col_idx = info['cat_col_idx']
column_names = info['column_names']

In [22]:
num_columns = [column_names[i] for i in num_col_idx]
cat_columns = [column_names[i] for i in cat_col_idx]

In [23]:
num_columns

['age',
 'fnlwgt',
 'education.num',
 'capital.gain',
 'capital.loss',
 'hours.per.week']

In [31]:
column_names

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education.num',
 'marital.status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital.gain',
 'capital.loss',
 'hours.per.week',
 'native.country',
 'income']

In [47]:
train_df.columns = column_names

In [48]:
train_df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [28]:
if info['test_path']:
    # if testing data is given
    test_path = info['test_path']

    with open(test_path, 'r') as f:
        lines = f.readlines()[1:]
        test_save_path = f'data/{name}/test.data'
        if not os.path.exists(test_save_path):
            with open(test_save_path, 'a') as f1:     
                for line in lines:
                    save_line = line.strip('\n').strip('.')
                    f1.write(f'{save_line}\n')

    test_df = pd.read_csv(test_save_path, header = None)

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/adult/adult.test'

In [ ]:
def handle_missing_value(df, num_columns, cat_columns):
    """
    Missing values are represented with a '?'.
    Replace 'P' with np.nan for numerical columns and 'nan' for string columns
    """
    for col in num_columns:
        train_df.loc[train_df[col] == '?', col] = np.nan
    for col in cat_columns:
        train_df.loc[train_df[col] == '?', col] = 'nan'
    for col in num_columns:
        test_df.loc[test_df[col] == '?', col] = np.nan
    for col in cat_columns:
        test_df.loc[test_df[col] == '?', col] = 'nan'

In [35]:
for col in num_columns:
    print(col)

age
fnlwgt
education.num
capital.gain
capital.loss
hours.per.week

In [51]:
train_df[train_df["workclass"] == '?']

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
61,32,?,293936,7th-8th,4,Married-spouse-absent,?,Not-in-family,White,Male,0,0,40,?,<=50K
69,25,?,200681,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
106,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K

In [49]:
train_df["workclass"].to_list()[:30]

['State-gov',
 'Self-emp-not-inc',
 'Private',
 'Private',
 'Private',
 'Private',
 'Private',
 'Self-emp-not-inc',
 'Private',
 'Private',
 'Private',
 'State-gov',
 'Private',
 'Private',
 'Private',
 'Private',
 'Self-emp-not-inc',
 'Private',
 'Private',
 'Self-emp-not-inc',
 'Private',
 'Private',
 'Federal-gov',
 'Private',
 'Private',
 'Local-gov',
 'Private',
 '?',
 'Private',
 'Private']

In [50]:
train_df["occupation"].to_list()[:30]

['Adm-clerical',
 'Exec-managerial',
 'Handlers-cleaners',
 'Handlers-cleaners',
 'Prof-specialty',
 'Exec-managerial',
 'Other-service',
 'Exec-managerial',
 'Prof-specialty',
 'Exec-managerial',
 'Exec-managerial',
 'Prof-specialty',
 'Adm-clerical',
 'Sales',
 'Craft-repair',
 'Transport-moving',
 'Farming-fishing',
 'Machine-op-inspct',
 'Sales',
 'Exec-managerial',
 'Prof-specialty',
 'Other-service',
 'Farming-fishing',
 'Transport-moving',
 'Tech-support',
 'Tech-support',
 'Craft-repair',
 '?',
 'Exec-managerial',
 'Craft-repair']