# Yeast

Link: https://archive.ics.uci.edu/dataset/110/yeast 

Is normally a multicalss dataset, but can be used to test different imbalanced ratios
in SMOTified-GAN CYT vs. ME2

In [9]:
import pandas as pd
from ucimlrepo import fetch_ucirepo
import numpy as np
from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)

In [2]:
# fetch dataset 
yeast = fetch_ucirepo(id=110) 
  
# data (as pandas dataframes) 
X = yeast.data.features 
y = yeast.data.targets

In [3]:
yeast.metadata

{'uci_id': 110,
 'name': 'Yeast',
 'repository_url': 'https://archive.ics.uci.edu/dataset/110/yeast',
 'data_url': 'https://archive.ics.uci.edu/static/public/110/data.csv',
 'abstract': 'Predicting the Cellular Localization Sites of Proteins',
 'area': 'Biology',
 'tasks': ['Classification'],
 'characteristics': ['Multivariate'],
 'num_instances': 1484,
 'num_features': 8,
 'feature_types': ['Real'],
 'demographics': [],
 'target_col': ['localization_site'],
 'index_col': ['Sequence_Name'],
 'has_missing_values': 'no',
 'missing_values_symbol': None,
 'year_of_dataset_creation': 1991,
 'last_updated': 'Sat Oct 28 2023',
 'dataset_doi': '10.24432/C5KG68',
 'creators': ['Kenta Nakai'],
 'intro_paper': None,
 'additional_info': {'summary': 'Predicted Attribute: Localization site of protein. ( non-numeric ).\r\n\r\nThe references below describe a predecessor to this dataset and its development. They also give results (not cross-validated) for classification by a rule-based expert system with that version of the dataset.\r\n\r\nReference: "Expert Sytem for Predicting Protein Localization Sites in Gram-Negative Bacteria", Kenta Nakai & Minoru Kanehisa,  PROTEINS: Structure, Function, and Genetics 11:95-110, 1991.\r\n\r\nReference: "A Knowledge Base for Predicting Protein Localization Sites in Eukaryotic Cells", Kenta Nakai & Minoru Kanehisa, Genomics 14:897-911, 1992.',
  'purpose': None,
  'funded_by': None,
  'instances_represent': None,
  'recommended_data_splits': None,
  'sensitive_data': None,
  'preprocessing_description': None,
  'variable_info': None,
  'citation': None}}

In [4]:
# combine features and targets
df = pd.concat([X, y], axis=1)

In [5]:
df

       mcg   gvh   alm   mit  erl  pox   vac   nuc localization_site
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22               MIT
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22               MIT
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22               MIT
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22               NUC
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22               MIT
...    ...   ...   ...   ...  ...  ...   ...   ...               ...
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22               ME2
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47               NUC
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22               ME2
1482  0.43  0.40  0.60  0.16  0.5  0.0  0.53  0.39               NUC
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22               CYT

[1484 rows x 9 columns]

In [6]:
# majority: CYT
df[(df["mcg"] == 0.51) & (df["gvh"] == 0.4)]

       mcg  gvh   alm   mit  erl  pox   vac   nuc localization_site
5     0.51  0.4  0.56  0.17  0.5  0.5  0.49  0.22               CYT
1034  0.51  0.4  0.50  0.28  0.5  0.0  0.48  0.27               CYT

In [7]:
# minority: ME2
df[(df["mcg"] == 0.67) & (df["gvh"] == 0.57)]

       mcg   gvh   alm   mit  erl  pox   vac   nuc localization_site
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22               ME2

In [10]:
# create dataset
df_maj = df[df["localization_site"] == "CYT"]
df_min = df[df["localization_site"] == "ME2"]

df_final = pd.concat([df_maj, df_min])

In [11]:
df_final

       mcg   gvh   alm   mit  erl  pox   vac   nuc localization_site
5     0.51  0.40  0.56  0.17  0.5  0.5  0.49  0.22               CYT
9     0.40  0.39  0.60  0.15  0.5  0.0  0.58  0.30               CYT
12    0.40  0.42  0.57  0.35  0.5  0.0  0.53  0.25               CYT
15    0.46  0.44  0.52  0.11  0.5  0.0  0.50  0.22               CYT
16    0.47  0.39  0.50  0.11  0.5  0.0  0.49  0.40               CYT
...    ...   ...   ...   ...  ...  ...   ...   ...               ...
1403  0.69  0.57  0.39  0.19  0.5  0.0  0.48  0.39               ME2
1434  0.86  0.78  0.34  0.15  0.5  0.0  0.53  0.22               ME2
1439  0.63  0.71  0.44  0.53  0.5  0.0  0.52  0.22               ME2
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22               ME2
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22               ME2

[514 rows x 9 columns]

In [ ]:
X = df_final.iloc[:, :-1]
y = df_final["localization_site"]

X_train, X_test, y_train, y_test = train_test_split()

In [8]:
# save df to csv
df.to_csv("../data/raw/yeast.csv", index=False)

In [8]:
data_path = "../data/raw/yeast.csv"

In [9]:
class_col = "localization_site"

In [10]:
df = pd.read_csv(data_path)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mcg                1484 non-null   float64
 1   gvh                1484 non-null   float64
 2   alm                1484 non-null   float64
 3   mit                1484 non-null   float64
 4   erl                1484 non-null   float64
 5   pox                1484 non-null   float64
 6   vac                1484 non-null   float64
 7   nuc                1484 non-null   float64
 8   localization_site  1484 non-null   object
dtypes: float64(8), object(1)
memory usage: 104.5+ KB

In [12]:
df

       mcg   gvh   alm   mit  erl  pox   vac   nuc localization_site
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22               MIT
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22               MIT
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22               MIT
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22               NUC
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22               MIT
...    ...   ...   ...   ...  ...  ...   ...   ...               ...
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22               ME2
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47               NUC
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22               ME2
1482  0.43  0.40  0.60  0.16  0.5  0.0  0.53  0.39               NUC
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22               CYT

[1484 rows x 9 columns]

In [13]:
print(df.isnull().sum())

mcg                  0
gvh                  0
alm                  0
mit                  0
erl                  0
pox                  0
vac                  0
nuc                  0
localization_site    0
dtype: int64

In [14]:
df[class_col].value_counts(normalize=True)

localization_site
CYT    0.311995
NUC    0.289084
MIT    0.164420
ME3    0.109838
ME2    0.034367
ME1    0.029650
EXC    0.023585
VAC    0.020216
POX    0.013477
ERL    0.003369
Name: proportion, dtype: float64

In [15]:
df[class_col].value_counts(normalize=False)

localization_site
CYT    463
NUC    429
MIT    244
ME3    163
ME2     51
ME1     44
EXC     35
VAC     30
POX     20
ERL      5
Name: count, dtype: int64

Class imbalance ratio: 0.001727%

In [8]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Class imbalance ration:", df[class_col].value_counts(normalize=True)[1])
print("Type of columns: mix of object and int, preprocessing is requiered")
print("Null values are present in the dataset")

Number of rows: 48842
Number of columns: 15
Class imbalance ration: 0.25459645387166785
Type of columns: mix of object and int, preprocessing is requiered
Null values are present in the dataset

/var/folders/gv/d21k9b7d7v9d382g4l3v4rqm0000gn/T/ipykernel_9851/3136583214.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Class imbalance ration:", df[class_col].value_counts(normalize=True)[1])